name: Troubleshooting JS Actions
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'User name'
        required: true
        default: 'Sid'
        type: string
      phone:
        description: 'Phone Number'
        required: true
        default: 9876543210
        type: number
      country:
        description: 'User Country'
        required: true
        default: 'india'
        type: choice
        options:
          - india
          - usa
          - others  

jobs:
  custom-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Invoking Greeting Action
      id: action_step
      uses: ./
      with:
        name: ${{ inputs.name }}
        phone: ${{ inputs.phone }}
        country: ${{ inputs.country }}

    - name: Log Data from Previous Step
      run: |
          echo "Output is: ${{ steps.action_step.outputs.customized_greeting }}"
          echo "Variable - $JS_ACTION_PHONE_VAR"