on:
  push:
  pull_request: 
        types:
         - opened

jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Post PR Comment
      id: test_step
      uses: ./
      with:
        name: 'revz'
        phone: '9876543210'
        country: 'india'

    - name: Post PR Comment2222222
      run: |
          echo "Output is: ${{ steps.test_step.outputs.customized_greeting }}""
          echo $JS_ACTION_PHONE_VAR