on:
  workflow_dispatch:
    inputs:
      name:
        description: 'User name'
        required: true
        default: 'Sid'
        type: string
      phone:
        description: 'Phone Number'
        required: true
        default: 9876543210
        type: number
      country:
        description: 'User Country'
        required: true
        default: 'india'
        type: choice
        options:
          - india
          - usa
          - others  

jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Post PR Comment
      id: test_step
      uses: ./
      with:
        name: ${{ inputs.name }}
        phone: ${{ inputs.phone }}
        country: ${{ inputs.country }}

    - name: Post PR Comment2222222
      run: |
          echo "Output is: ${{ steps.test_step.outputs.customized_greeting }}""